on: [push]

name: Sogrim-CI

env:
  CARGO_TERM_COLOR: always
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
  SOMEVAR: ${{secrets.SOME_VAR}}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: rymndhng/release-on-push-action@master
