on: [push, pull_request]

name: Sogrim-CI

env:
  CARGO_TERM_COLOR: always

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path pacakges/server/Cargo.toml

  test:
    name: Run Tests
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path pacakges/server/Cargo.toml

  lints:
    name: Format + Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Check cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path pacakges/server/Cargo.toml --all -- --check

      - name: Check cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path pacakges/server/Cargo.toml -- -D warnings

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    needs: [compile, test, lints]
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sh-ops-server" #Must be unique in Heroku
          heroku_email: "benick12@gmail.com"