on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'

name: Echo 1

jobs:
  echo-one:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Echo 1
      id: toolchain
      run: |
        rust_toolchain="$(cat rust-toolchain)"
        echo "RUST_TOOLCHAIN<<EOF"$'\n'"$rust_toolchain"$'\n'EOF >> "$GITHUB_OUTPUT"

    - name: Build images
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        build-args: |
            "RUST_TOOLCHAIN=${{ steps.toolchain.outputs.RUST_TOOLCHAIN }}"

