on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'

name: Echo 1

jobs:
  echo-one:
    name: Echo 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          {
            echo 'RUST_TOOLCHAIN<<EOF'
            cat rust-toolchain
            echo EOF
          } >> "$GITHUB_ENV"

  echo-env:
    name: Echo the environment
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ env.RUST_TOOLCHAIN }}"
