on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'

name: Echo 1

jobs:
  echo-one:
    name: Echo 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Echo 1"
