on:
  push:
    branches:
      - master # TODO someday will probably need to be renamed into 'main'

name: Echo 2

jobs:
  echo-two:
    name: Echo 2
    needs: Echo 1
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Echo 2"
